global:
  enabled: true
  name: consul
  datacenter: ${datacenter}
  image: "hashicorp/consul-enterprise:1.17.1-ent"
  peering:
    enabled: true
  tls:
    enabled: true # mandatory for cluster peering
    enableAutoEncrypt: true
    verify: true
    caCert:
      secretName: ${cluster_id}-hcp
      secretKey: caCert
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: ${cluster_id}-hcp
      secretKey: bootstrapToken

  metrics:
    enabled: true
    enableGatewayMetrics: true

dns:
  enabled: true
  enableRedirection: true

externalServers:
  enabled: true
  hosts: ["${consul_hosts}"]
  httpsPort: 443
  useSystemRoots: true
  k8sAuthMethodHost: ${k8s_api_endpoint}:443

server:
  enabled: false

connectInject:
  transparentProxy:
    defaultEnabled: true
  enabled: true
  default: true
  metrics:
    defaultEnabled: true # by default, this inherits from the value global.metrics.enabled
    defaultEnableMerging: false
  apiGateway:
    managedGatewayClass:
      serviceType: LoadBalancer
  consulNode:
    meta:
      terraform-module: "hcp-eks-client"

meshGateway:
  enabled: true # mandatory for k8s cluster peering
  replicas: 1

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
  metrics:
    enabled: true # by default, this inherits from the value global.metrics.enabled
    provider: "prometheus"
    baseURL: http://prometheus-server #prometheus-server.consul.svc.cluster.local

prometheus:
  enabled: true
