apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default # partition containing services to export
spec:
  services:
    - name: frontend
      consumers:
        - samenessGroup: sameness-group-hashicups
    - name: public-api
      consumers:
        - samenessGroup: sameness-group-hashicups
    - name: products-api
      consumers:
        - samenessGroup: sameness-group-hashicups
