---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: public-api
  namespace: default
spec:
  sources:
  - name: nginx
    namespace: default
    samenessGroup: sameness-group-hashicups
    action: allow
  - name: nginx
    namespace: default
    action: allow
  - name: frontend
    namespace: default
    samenessGroup: sameness-group-hashicups
    action: allow
  - name: frontend
    namespace: default
    action: allow
  - name: consul-api-gateway
    namespace: consul
    action: allow
  destination:
    name: public-api
