---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
spec:
  destination:
    name: frontend
  sources:
  - name: nginx
    action: allow
    samenessGroup: product-group
  - name: nginx
    action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: public-api
spec:
  destination:
    name: public-api
  sources:
  - name: nginx
    action: allow
    samenessGroup: product-group
  - name: nginx
    action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: products-api
spec:
  destination:
    name: products-api
  sources:
  - name: public-api
    action: allow
    samenessGroup: product-group
  - name: public-api
    action: allow
